### ISSUE TITLE
Extensions - Unity Official Tutorials-jpn.srt

### ISSUE THREAD

**Issue by anchan828** [unity3d-jp/LearnSubtitles#156]
翻訳の確認をお願いします。
一部、未翻訳の場合は翻訳を、翻訳に誤りがある場合は修正をお願いします。

**Comment by RyutaYazawa** [comment]
@anchan828  Extension Methods-jpn.srt #181　と内容が同じだったので最新の内容をコピペしておきました。

**Comment by anchan828** [comment]
おっと、了解です。
