### ISSUE TITLE
Polymorphism - Unity Official Tutorials-jpn.srt

### ISSUE THREAD

**Issue by anchan828** [unity3d-jp/LearnSubtitles#165]
翻訳の確認をお願いします。
一部、未翻訳の場合は翻訳を、翻訳に誤りがある場合は修正をお願いします。

**Comment by RyutaYazawa** [comment]
@anchan828 すみません、この項目については重点的に翻訳をチェックいただけますと幸いです、理解が追い付いていない箇所があります
