### ISSUE TITLE
Building a Custom Inspector - Unity Official Tutorials-jpn.srt

### ISSUE THREAD

**Issue by anchan828** [unity3d-jp/LearnSubtitles#211]
翻訳の確認をお願いします。一部、未翻訳の場合は翻訳を、翻訳に誤りがある場合は修正をお願いします。[Building a Custom Inspector - Unity Official Tutorials-jpn.srt](../blob/master/Topics/Intermediate/Editor/Japanese/Building a Custom Inspector - Unity Official Tutorials-jpn.srt)

**Comment by RyutaYazawa** [comment]
@anchan828 こちらのファイル（
GitHub\LearnSubtitles\Topics\Intermediate\Editor\Japanese\Building a Custom Inspector - Unity Official Tutorials-jpn.srt"）、原文のテキスト起こしが途中で終わっています。ご確認のうえ、再度ファイル起こし処理お願いします！

翻訳はひとまず中断して、他のファイルを優先します。
