### ISSUE TITLE
Unity Animation 字幕翻訳

### ISSUE THREAD

**Issue by anchan828** [unity3d-jp/LearnSubtitles#226]
フォルダー内の全ての翻訳をお願いします。
https://github.com/unity3d-jp/LearnSubtitles/tree/master/Engine/Topics/Animation

* Animation Curves and Events - Unity Official Tutorials.srt
* Animation Properties - Unity Official Tutorials.srt
* The Animation View - Unity Official Tutorials.srt
* Avatar Masks - Unity Official Tutorials.srt
* Humanoid Avatars - Unity Official Tutorials.srt
* Animator Controller Layers - Unity Official Tutorials.srt
* Animator Scripting - Unity Official Tutorials.srt
* Animator Sub-state machine hierarchies - Unity Official Tutorials.srt
* Blend Trees - Unity Official Tutorials.srt
* The Animator Component - Unity Official Tutorials.srt
* The Animator Controller - Unity Official Tutorials.srt

**Comment by RyutaYazawa** [comment]
@anchan828 225 Tips が完了したのですが、引き続きこちら進めていっても大丈夫でしょうか? 作業はOK頂いてからスタートします!

**Comment by anchan828** [comment]
細かいですが、一部、「取得する」という意味で「取ります」となっていたので取得するに統一しました

**Comment by anchan828** [comment]
色々修正しましたー！のでチェックしていただけると...!!

**Comment by RyutaYazawa** [comment]
ありがとうございます、確認しました！
特にアニメーションは理解が難しい箇所があり、そのせいかケアレスミスも出てしまっておりました…失礼しました

**Comment by anchan828** [comment]
逆にケアレスミスくらいしか見つけられなくて、すんなり理解できるすばらしい文章で大変助かります。

**Comment by RyutaYazawa** [comment]
よかったです…！いただいた言葉を励みに引き続きがんばりますー
